### ISSUE TITLE
Commitが正常に動かない

### ISSUE THREAD

**Issue by nikuuchi** [konoha-project/AssuranceScriptEditor#20]
コミット時に発行される仮IDの挙動がおかしいです。JavaScript難しい

**Comment by nikuuchi** [comment]
insertが直りました。 b31d868

**Comment by wakamori** [comment]
仮IDの発行のバグという部分を追ってみます。

**Comment by wakamori** [comment]
バグの詳細ですが、１度のコミットで同じノードを複数回編集した際にツリーが消えるという現象を確認しました。上記の仮ID関係のバグです。

**Comment by nikuuchi** [comment]
ad hocなテーブルで対応しました.これから設計を練り直そうと思います。
