### ISSUE TITLE
パーマリンク

### ISSUE THREAD

**Issue by nikuuchi** [konoha-project/AssuranceScriptEditor#57]

**Comment by nikuuchi** [comment]
createDCaseの時もAjaxではなくパーマリンクへの移動で表現したらいいと思います。

**Comment by wakama2** [comment]
index.php?dcaseId=n へ移動みたいな形ですかね，その辺の仕様を固めましょう

**Comment by nikuuchi** [comment]
index.php?dcaseId=nが動きました abd7a6b
